workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      vars:
        XCODE_PROJECT: "iosApp/iosApp.xcodeproj"
        XCODE_SCHEME: "iosApp"
      node: latest
      xcode: latest
    scripts:
      - name: Set up Gradle
        script: chmod +x gradlew
      - name: Build Shared Framework (Simulator)
        script: |
          ./gradlew clean :shared:assembleSharedDebugFrameworkIosSimulatorArm64 --stacktrace
      - name: Install XcodeGen
        script: brew install xcodegen
      - name: Generate Xcode Project
        script: |
          cd iosApp
          xcodegen generate
      - name: Build iOS App
        script: |
          xcodebuild build -project iosApp/iosApp.xcodeproj -scheme iosApp -sdk iphonesimulator -configuration Debug
    artifacts:
      - iosApp/*.app
      - iosApp/*.ipa
      - shared/build/bin/iosSimulatorArm64/debugFramework/Shared.framework
