platform :ios, '15.0'

target 'iosApp' do
  use_frameworks!

  pod 'shared', :path => '../shared'
  pod 'FirebaseCore', '10.0.0'
  pod 'FirebaseAuth', '10.0.0'
  pod 'FirebaseFirestore', '10.0.0'
  pod 'FirebaseStorage', '10.0.0'
end
