name: iosApp
options:
  bundleIdPrefix: com.aspigon1.mvdm
targets:
  iosApp:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources: [iosApp]
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.aspigon1.mvdm.iosApp
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    dependencies:
      - sdk: Shared.framework
        path: ../shared/build/cocoapods/framework/Shared.framework
