name: iosApp
options:
  bundleIdPrefix: com.aspigon1.mvdm
targets:
  iosApp:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources: [iosApp]
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.aspigon1.mvdm.iosApp
      FRAMEWORK_SEARCH_PATHS: $(inherited) $(PROJECT_DIR)/../shared/build/bin/iosArm64/releaseFramework
    dependencies:
      - framework: ../shared/build/bin/iosArm64/releaseFramework/Shared.framework
        embed: true
